### ISSUE TITLE
Not able to run simple program using this library

### ISSUE THREAD

**Issue by Weltspear** [OpenGrabeso/glg2d#5]
When running my program I get the following exception:
```java
Exception in thread "main" java.lang.IllegalAccessError: superinterface check failed: class net.opengrabeso.glg2d.LWJGLComponentPeer (in unnamed module @0xe320068) cannot access class java.awt.peer.ComponentPeer (in module java.desktop) because module java.desktop does not export java.awt.peer to unnamed module @0xe320068
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.opengrabeso.glg2d.GLG2DPanelLWJGL.loop(GLG2DPanelLWJGL.java:166)
	at net.opengrabeso.glg2d.GLG2DPanelLWJGL.run(GLG2DPanelLWJGL.java:37)
	at net.suptest.Main.main(Main.java:10)
```

Source code:
`Main.java`
```java
package net.suptest;

import net.opengrabeso.glg2d.GLG2DPanelLWJGL;


public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");

        new GLG2DPanelLWJGL(new TestComponent(), "Test").run();

    }
}
```
`TestComponent.java`
```java
package net.suptest;

import javax.swing.*;
import java.awt.*;

public class TestComponent extends JComponent {

    public TestComponent(){

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        g.setColor(Color.BLACK);

        g.fillRect(0, 0, 50, 50);

        g.dispose();
    }
}
```
I am using: IntelliJ, OpenJDK 17, Gradle

**Comment by OndrejSpanel** [comment]
Did you try running any of the examples from the repository, like `GLFWBasic`, `LWJGLG2DExampleCircles`  or `LWJGLlUIDemo`?

**Comment by OndrejSpanel** [comment]
One visible difference is examples override `paintComponent`, not `paint`.

**Comment by Weltspear** [comment]
> One visible difference is examples override `paintComponent`, not `paint`.

After replacing `paint` override with `paintComponent` override the exception is still thrown.

**Comment by OndrejSpanel** [comment]
I do not think you should  `g.dispose()` in `paint`. I suggest you to try starting from the examples and see what happens.

**Comment by Weltspear** [comment]
After directly copying and pasting: `https://github.com/OpenGrabeso/glg2d/blob/master/examples/src/main/java/net/opengrabeso/glg2d/examples/G2DExampleCircles.java` still getting the same exception

**Comment by Weltspear** [comment]
It is an issue with module access but I don't know how to give hidden module access to the library.

**Comment by OndrejSpanel** [comment]
I am not sure how can I help you then. The examples do work for me. I am not running with JDK 11 though, I use Java 8.

**Comment by Weltspear** [comment]
Actually after changing JDK version to 8 it started working, maybe `java.awt.peer` got deprecated or something

**Comment by OndrejSpanel** [comment]
You could be able to use use VM options `--illegal-access=warn` or `--illegal-access=permit` option as a temporary workaround.

**Comment by Weltspear** [comment]
I found out that `java.awt.peer` has been completely disabled in Java 9: [https://docs.oracle.com/en/java/javase/17/migrate/removed-apis.html#GUID-0C350BAB-F2C8-409E-AD3E-63831C684A55](https://docs.oracle.com/en/java/javase/17/migrate/removed-apis.html#GUID-0C350BAB-F2C8-409E-AD3E-63831C684A55)

**Comment by OndrejSpanel** [comment]
Thanks for the information. I will think about some way how to replace it.

**Comment by Weltspear** [comment]
Also an interesting thing if you run this program using `jbr-11` (JetBrains Runtime) Java throws a different exception:
```java
Exception in thread "main" java.lang.IllegalAccessError: superclass access check failed: class net.opengrabeso.glg2d.impl.AbstractTesselatorVisitor$TessellatorCallback (in unnamed module @0x7c469c48) cannot access class com.jogamp.opengl.glu.GLUtessellatorCallbackAdapter (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.glu to unnamed module @0x7c469c48
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.opengrabeso.glg2d.impl.AbstractTesselatorVisitor.<init>(AbstractTesselatorVisitor.java:50)
	at net.opengrabeso.glg2d.impl.shader.GL2ES2TesselatingVisitor.<init>(GL2ES2TesselatingVisitor.java:38)
	at net.opengrabeso.glg2d.impl.shader.GL2ES2TesselatingVisitor.<init>(GL2ES2TesselatingVisitor.java:35)
	at net.opengrabeso.glg2d.impl.shader.GL2ES2ShapeDrawer.<init>(GL2ES2ShapeDrawer.java:39)
	at net.opengrabeso.glg2d.impl.shader.GLShaderGraphics2D.createShapeHelper(GLShaderGraphics2D.java:59)
	at net.opengrabeso.glg2d.GLGraphics2D.createDrawingHelpers(GLGraphics2D.java:134)
	at net.opengrabeso.glg2d.GLGraphics2D.<init>(GLGraphics2D.java:122)
	at net.opengrabeso.glg2d.impl.shader.GLShaderGraphics2D.<init>(GLShaderGraphics2D.java:31)
	at net.opengrabeso.glg2d.GLG2DPanelLWJGL.loop(GLG2DPanelLWJGL.java:133)
	at net.opengrabeso.glg2d.GLG2DPanelLWJGL.run(GLG2DPanelLWJGL.java:37)
	at net.suptest.Main.main(Main.java:10)
```

**Comment by OndrejSpanel** [comment]
> Exception in thread "main" java.lang.IllegalAccessError: superinterface check failed: class net.opengrabeso.glg2d.LWJGLComponentPeer 

I get this error when running under Java 19 (I had to update LWJGL to avoid crash, though)

I am running all LWJGL examples fine under Java 17, as long as they are built with Java 8. Building with Java 11 is not possible at the moment.

The only reason why `peer` is used is this code:

```
                        ComponentPeer peer = new LWJGLComponentPeer();
                        // peer is necessary for validate - otherwise validateTree is not called
                        sun.awt.AWTAccessor.getComponentAccessor().setPeer(component, peer);
                        component.invalidate();
                        component.validate();
```

When trying to run JOGL versions of examples using Java 17, I get a different error:

> WARNING: Drawable component and children should be pure Swing: javax.swing.CellRendererPane[,0,0,0x0,invalid,hidden] does not inherit JComponent

**Comment by OndrejSpanel** [comment]
I have removed the obsolete code and I can run everything under Java 21. Most examples now work with both JOGL and LWJGL, some more complex only in JOGL.
